In [ ]:
import os
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torchtext.transforms as T
import torchtext.functional as F
from torchtext.datasets import SST2
from torch.utils.data import DataLoader
from torch.hub import load_state_dict_from_url
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
from google.colab import drive 
drive.mount('/content/drive')
os.chdir('/content/drive/MyDrive/STOR565 Project')

Mounted at /content/drive

In [ ]:
mbti = pd.read_csv('mbti_preprocessed_1.csv')

In [ ]:
mbti.head()

,Unnamed: 0,type,posts,processed_posts
0,0,INFJ,'http://www.youtube.com/watch?v=qsXHcwe3krw|||...,moment sportscenter top ten play pr...
1,1,ENTP,'I'm finding the lack of me in these posts ver...,finding lack post alarming sex boring positi...
2,2,INTP,'Good one _____ https://www.youtube.com/wat...,good one course say know blessing...
3,3,INTJ,"'Dear INTP, I enjoyed our conversation the o...",dear enjoyed conversation day esoteric ...
4,4,ENTJ,'You're fired.|||That's another silly misconce...,fired another silly misconception approachi...

In [ ]:
# Personality type for each aspect

# Extroversion vs. Introversion
mbti['EorI'] = mbti['type'].apply(lambda x: x[0])

# Intuition vs. Sensing
mbti['NorS'] = mbti['type'].apply(lambda x: x[1])

# Thinking vs. Feeling
mbti['TorF'] = mbti['type'].apply(lambda x: x[2])

# Judging vs. Perceiving
mbti['JorP'] = mbti['type'].apply(lambda x: x[3])

In [ ]:
mbti.head()

,Unnamed: 0,type,posts,processed_posts,EorI,NorS,TorF,JorP
0,0,INFJ,'http://www.youtube.com/watch?v=qsXHcwe3krw|||...,moment sportscenter top ten play pr...,I,N,F,J
1,1,ENTP,'I'm finding the lack of me in these posts ver...,finding lack post alarming sex boring positi...,E,N,T,P
2,2,INTP,'Good one _____ https://www.youtube.com/wat...,good one course say know blessing...,I,N,T,P
3,3,INTJ,"'Dear INTP, I enjoyed our conversation the o...",dear enjoyed conversation day esoteric ...,I,N,T,J
4,4,ENTJ,'You're fired.|||That's another silly misconce...,fired another silly misconception approachi...,E,N,T,J

In [ ]:
dataset_cleaned = mbti[["type", "processed_posts"]]
dataset_cleaned.to_csv('mbtiALL_cleaned.csv')

In [ ]:
dataset_cleaned.head()

   type                                    processed_posts
0  INFJ       moment    sportscenter top ten play    pr...
1  ENTP   finding lack post alarming  sex boring positi...
2  INTP   good one           course  say know  blessing...
3  INTJ   dear     enjoyed conversation day   esoteric ...
4  ENTJ   fired  another silly misconception  approachi...

In [ ]:
dataset = mbti[["type", "posts"]]
dataset.to_csv('mbtiALL.csv')

In [ ]:
dataset.head()

   type                                              posts
0  INFJ  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...
1  ENTP  'I'm finding the lack of me in these posts ver...
2  INTP  'Good one  _____   https://www.youtube.com/wat...
3  INTJ  'Dear INTP,   I enjoyed our conversation the o...
4  ENTJ  'You're fired.|||That's another silly misconce...

In [ ]:
datasetEorI = mbti[["EorI", "posts"]]
datasetEorI.to_csv('mbtiEorI.csv')

In [ ]:
datasetEorI.head()

  EorI                                              posts
0    I  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...
1    E  'I'm finding the lack of me in these posts ver...
2    I  'Good one  _____   https://www.youtube.com/wat...
3    I  'Dear INTP,   I enjoyed our conversation the o...
4    E  'You're fired.|||That's another silly misconce...

In [ ]:
datasetNorS = mbti[["NorS", "posts"]]
datasetNorS.to_csv('mbtiNorS.csv')

In [ ]:
datasetNorS.head()

  NorS                                              posts
0    N  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...
1    N  'I'm finding the lack of me in these posts ver...
2    N  'Good one  _____   https://www.youtube.com/wat...
3    N  'Dear INTP,   I enjoyed our conversation the o...
4    N  'You're fired.|||That's another silly misconce...

In [ ]:
datasetTorF = mbti[["TorF", "posts"]]
datasetTorF.to_csv('mbtiTorF.csv')

In [ ]:
datasetTorF.head()

  TorF                                              posts
0    F  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...
1    T  'I'm finding the lack of me in these posts ver...
2    T  'Good one  _____   https://www.youtube.com/wat...
3    T  'Dear INTP,   I enjoyed our conversation the o...
4    T  'You're fired.|||That's another silly misconce...

In [ ]:
datasetJorP = mbti[["JorP", "posts"]]
datasetJorP.to_csv('mbtiJorP.csv')

In [ ]:
datasetJorP.head()

  JorP                                              posts
0    J  'http://www.youtube.com/watch?v=qsXHcwe3krw|||...
1    P  'I'm finding the lack of me in these posts ver...
2    P  'Good one  _____   https://www.youtube.com/wat...
3    J  'Dear INTP,   I enjoyed our conversation the o...
4    J  'You're fired.|||That's another silly misconce...